### ISSUE TITLE
BLE: Case inconsistency

### ISSUE THREAD

**Issue by Ysbrand** [btsimonh/Tasmota#1]
J ust noticed something which will need some cleanup (ie inconsistent case):

In the sensor message the mac is in lower case
`SENSOR = {"Time":"2021-01-18T16:50:51","LYWSD03-08e3b3":{"MAC":"a4c13808e3b3`

In the BLE message the mac is in uppercase
`BLE = {"Time":"2021-01-18T16:50:59","BLEDevices":{"total":78,"4CA01DE4093F":{"i":54,"r":-35},"4D7870EEC3B8":`

**Comment by Ysbrand** [comment]
Same issue with EQ3:
`stat/ESP32-2/EQ3/001A2217044B = {"trv":"00:1a:22:17:04:4b","blestat`

**Comment by btsimonh** [comment]
i think this is basically solved?

**Comment by btsimonh** [comment]
haha reopen
