### ISSUE TITLE
EQ3: Cleanup schedule output

### ISSUE THREAD

**Issue by Ysbrand** [btsimonh/Tasmota#2]
As designed setprofile ignores everything after the 1st occurrence of 24:00.
Suggest to simplify the reqprofile output, only report values until we hit 24:00
Current output:
`profileday2":"23.5-24:00,17.0-24:00,17.0-24:00,17.0-24:00,17.0-24:00,17.0-24:00,17.0-24:00"`
Suggested outptut
`profileday2":"23.5-24:00"`
(Essentially ignore everything once we hit 90 (final event = 24:00)
the other "17.0-24:00" are just misleading as they are ignored by the TRV anyway.

**Comment by btsimonh** [comment]
done
