### ISSUE TITLE
Home Assistant & MI sensors.

### ISSUE THREAD

**Issue by btsimonh** [btsimonh/Tasmota#3]
Home Assistant & MI sensors.

1/ we don't add TempUnit, etc. to the tele/TAS/sensors msgs.
I don't think this is an issue for HA, since they seem to configure that at HA end?

2/ 'new discovery' does not trigger us sending. 
Q: does HA HAVE to have all sensors in one (retained?) msg?

3/ Tas integration adds '8 blank sensors' - not good if we have > 8?

4/ Sensor names - if we can set the name of the pvvx sensor, should that be the sensor name used rather than some mac-based thing?

**Comment by btsimonh** [comment]
Discovery:

Currently TAS has a specific HA driver which drives discovery.
This works fine for statically attached sensors, but with the MI sensors, they are not statically attached, and can 'add' themselves or remove themselves from TAS dynamically.

The HA mqtt discovery protocol is well documented here https://www.home-assistant.io/docs/mqtt/discovery/

For a true 'plug and play' experience, we need to match our MQTT output to the HA discovery requirements, and in theory this should create devices with little or no user intervention.

There seems no reason not to send HA discovery packets fairly regularly..  HA states that this is OK?
But it does seem apparent that it would prefer one MQTT per sensor - and if we send in the right form, no manual configuration of HA and no plugin should be required.

One major question would be what happens when a sensor is 'heard' by two TAS, and so discovered coming from two places in HA.  We could give each sensor a unique ID based on the combination of the TAS mac/ip and the sensor MAC?

Naming sensors based on BLEAlias, or even BLE name may be appropriate.

Can HA carry a link to the TAS configuration page for a TAS module?

**Comment by Ysbrand** [comment]
Discussion on a new way of doing discovery:
[https://github.com/arendst/Tasmota/issues/9267]

Generic info on MQTT
[discovery:](https://www.home-assistant.io/docs/mqtt/discovery/)

I've looked at zigbee2mqtt as it is essentially also a gateway from external sensors to MQTT. The difference is that with zigbee2mqqt  you define the sensors which will be send to mqtt:
![image](https://user-images.githubusercontent.com/16001552/105524638-31a10d00-5ce0-11eb-845b-f8fe84ba073d.png)

Once that has done it will send the discovery messages through mqtt (example for the 1st sensor):

homeassistant/sensor/0x00158d00054cb213/battery/config
`{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/Aqara Slaapkamer/availability"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00054cb213"],"manufacturer":"Xiaomi","model":"Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)","name":"Aqara Slaapkamer","sw_version":"Zigbee2MQTT 1.17.0"},"device_class":"battery","json_attributes_topic":"zigbee2mqtt/Aqara Slaapkamer","name":"Aqara Slaapkamer battery","state_topic":"zigbee2mqtt/Aqara Slaapkamer","unique_id":"0x00158d00054cb213_battery_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}`

homeassistant/sensor/0x00158d00054cb213/humidity/config
`{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/Aqara Slaapkamer/availability"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00054cb213"],"manufacturer":"Xiaomi","model":"Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)","name":"Aqara Slaapkamer","sw_version":"Zigbee2MQTT 1.17.0"},"device_class":"humidity","json_attributes_topic":"zigbee2mqtt/Aqara Slaapkamer","name":"Aqara Slaapkamer humidity","state_topic":"zigbee2mqtt/Aqara Slaapkamer","unique_id":"0x00158d00054cb213_humidity_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.humidity }}"}`

homeassistant/sensor/0x00158d00054cb213/linkquality/config
`{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/Aqara Slaapkamer/availability"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00054cb213"],"manufacturer":"Xiaomi","model":"Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)","name":"Aqara Slaapkamer","sw_version":"Zigbee2MQTT 1.17.0"},"icon":"mdi:signal","json_attributes_topic":"zigbee2mqtt/Aqara Slaapkamer","name":"Aqara Slaapkamer linkquality","state_topic":"zigbee2mqtt/Aqara Slaapkamer","unique_id":"0x00158d00054cb213_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}`

homeassistant/sensor/0x00158d00054cb213/pressure/config
`{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/Aqara Slaapkamer/availability"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00054cb213"],"manufacturer":"Xiaomi","model":"Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)","name":"Aqara Slaapkamer","sw_version":"Zigbee2MQTT 1.17.0"},"device_class":"pressure","json_attributes_topic":"zigbee2mqtt/Aqara Slaapkamer","name":"Aqara Slaapkamer pressure","state_topic":"zigbee2mqtt/Aqara Slaapkamer","unique_id":"0x00158d00054cb213_pressure_zigbee2mqtt","unit_of_measurement":"hPa","value_template":"{{ value_json.pressure }}"}`

homeassistant/sensor/0x00158d00054cb213/temperature/config
`{"availability":[{"topic":"zigbee2mqtt/bridge/state"},{"topic":"zigbee2mqtt/Aqara Slaapkamer/availability"}],"device":{"identifiers":["zigbee2mqtt_0x00158d00054cb213"],"manufacturer":"Xiaomi","model":"Aqara temperature, humidity and pressure sensor (WSDCGQ11LM)","name":"Aqara Slaapkamer","sw_version":"Zigbee2MQTT 1.17.0"},"device_class":"temperature","json_attributes_topic":"zigbee2mqtt/Aqara Slaapkamer","name":"Aqara Slaapkamer temperature","state_topic":"zigbee2mqtt/Aqara Slaapkamer","unique_id":"0x00158d00054cb213_temperature_zigbee2mqtt","unit_of_measurement":"°C","value_template":"{{ value_json.temperature }}"}`

**Comment by btsimonh** [comment]
Notes on test version (tasmota32-sensors-MQTT-HASS-DISCOVERY-MI.bin):
Enable HA discovery with setoption19 1

discovery messages like (one for each data entry):
```
12:08:14.157 MQT: homeassistant/sensor/LYWSD037fc1e1/Battery/config = {"availability":[],"device": {"identifiers":["BLELYWSD037fc1e1"],"name":"LYWSD037fc1e1","manufacturer":"tas","model":"LYWSD03","via_device":"tasmota_esp32-7832"}, "dev_cla":"battery","expire_after":600,"json_attr_t":"tele/tasmota_ble/LYWSD037fc1e1","name":"LYWSD037fc1e1_Battery","state_topic":"tele/tasmota_ble/LYWSD037fc1e1","uniq_id":"LYWSD037fc1e1_Battery","unit_of_meas":"%","val_tpl":"{{ value_json.Battery }}"}
```

additional data messages like:
```
12:08:14.242 MQT: tele/tasmota_ble/LYWSD037fc1e1 = {"Time":"2021-01-24T12:08:14","mac":"a4c1387fc1e1","Temperature":21.2,"Humidity":40.0,"DewPoint":7.1,"Battery":71,"RSSI":-34}
```

Both are sent every MIPeriod (which defaults to teleperiod at startup).


NOTE:
Every tasmota which hears LYWSD037fc1e1 will produce the SAME topic for that sensor.
You can override this by using BLEAlias to change the name, e.g.
`BLEAlias a4c1387fc1e1=fred`
Changes every entry in the messages above where 'LYWSD037fc1e1' occurs to use 'fred' instead.

**Comment by clau-bucur** [comment]
I find that a whitelist/blacklist option would be helpful.
We might want to only process certain devices, or even ignore specific ones.

For example I don't want to read my neighbours temperature.
Or, I have a well defined list of mac addresses I want to read data from, and I don't care about anything else.

**Comment by btsimonh** [comment]
@clau-bucur - agree to some degree.
MI32Block is still there, so you can ban some addresses.
I'm thinking an option 'only hear things which have aliases' would serve as a white list, maybe? (and not too difficult to implement and describe).
You would still be able to see ALL Ble devices in the Configure BLE, so adding a new one would be fairly easy.
Maybe the 'Alias' field in ConfigureBLE should be editable!!!! (joking - not worth it for what is a one-time operation)

**Comment by clau-bucur** [comment]
> MI32Block is still there, so you can ban some addresses.
> I'm thinking an option 'only hear things which have aliases' would serve as a white list, maybe? (and not too difficult to implement and describe).

Yep, it would do the job nicely.

**Comment by btsimonh** [comment]
interesting HA topic on zigbee and tasmota.  So we're not 'not the tasmota way' - we are very close to the zigbee code?
https://community.home-assistant.io/t/mqtt-demultiplexer-automatic-sensor-discovery-for-tasmota2zigbee/237900

**Comment by btsimonh** [comment]
Working sufficiently well now, so closing
