### ISSUE TITLE
EQ3 command queueing

### ISSUE THREAD

**Issue by Ysbrand** [btsimonh/Tasmota#5]
At the moment there is no real command queueing in the EQ3 implementation.
Logic:

1. We send a command
2. Get a response queued
3. BLE scan process is aborted
4. Send the command to the TRV retry max 3 times
5. Send the status DONE/FAIL

There are 2 issues with this approach
- While the trv command is processed other trv commands are rejected. Which implies that one has to implement some retry logic at the requesting host (which is not always easy)
- As the scan process is preliminary aborted we might miss sensor updates

Some basic queueing logic might address some of the issues.
Suggested logic:

1. Collect incoming EQ3 requests, reject if the queue if full (not sure what is reasonable)
2. Once a scan period is over, check if there are any requests in the queue
3. Process requests FIFO  (including the current retry logic) and report back DONE/FAIL

We could set a maximum nr of requests to handle during a single run for instance
- 2 independent requests without any retries needed
- 1 requests which requires more than 1 retry
- This wil depend on how long it's acceptable to stop the scanning
4. Start a new scan period

**Comment by btsimonh** [comment]
mostly done but still under review; posting to keep issue active
