### ISSUE TITLE
EQ TRV values on default tasmota webpage

### ISSUE THREAD

**Issue by kroon040** [btsimonh/Tasmota#7]
Hi,

Is it possible to show the values on the default webpage form tasmota. Just like other bluetooth values of like zigbee with nice icons.

![radiator](https://user-images.githubusercontent.com/40452265/111898510-cc8b3e80-8a26-11eb-826a-1886e764b8bc.png)

![mi esp](https://user-images.githubusercontent.com/40452265/111898464-7f0ed180-8a26-11eb-9ce2-8bb0eb56d30b.png)

**Comment by btsimonh** [comment]
ohh..  that looks quite nice - was not aware of such things as I've not look at the TAS zigbee code in much detail.
Certainly, the BLE sensors would benefit - the display at the moment takes up far too much room, and the paging is a pain - plus the fact it drives the buttons to move up and down (I'd prefer the sensors to sit BELOW the menus).
For EQ3 also - if each was represented on a single line, they too could live in the 'sensors' zone....

nice idea, not sure if I will have the time to get around to it - maybe bring it up on discord and if we could enlist some help?
