### ISSUE TITLE
Is EQ3 TRV supported in latest public release of Tasmota?

### ISSUE THREAD

**Issue by jperquin** [btsimonh/Tasmota#8]
### PROBLEM DESCRIPTION
_A clear and concise description of what the problem is._

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [ ] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [ ] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [ ] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [ ] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [ ] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [ ] Device used (e.g., Sonoff Basic): _____
- [ ] Tasmota binary firmware version number used: _____
  - [ ] Pre-compiled
  - [ ] Self-compiled
- [ ] Flashing tools used: _____
- [ ] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:


```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [ ] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:


```
- [ ] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:


```

### TO REPRODUCE
_Steps to reproduce the behavior:_

### EXPECTED BEHAVIOUR
_A clear and concise description of what you expected to happen._

### SCREENSHOTS
_If applicable, add screenshots to help explain your problem._

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by Ysbrand** [comment]
No, the PR has not been submitted, and as such it is not part of the Tasmota release (yet).

**Comment by jperquin** [comment]
Thanks Ysbrand.

Figured I should compile my own then. Went the gitpod route, but am a complete noob at that.

I created a new workspace in gitpod with https://github.com/btsimonh/Tasmota/tree/EQ3-2021-09-06/tasmota, and ran platformio run -e tasmota32-bluetooth, which compiles without the EQ3 drivers..

Any pointers are welcome..

Thanks Joost

**Comment by Ysbrand** [comment]
Never used it before. Based on my own builds I would say:

platformio_override.ini:
disable tasmota
enable
tasmota32-bluetooth

tasmota/user_config_override.h
add:
#undef USE_EQ3_ESP32                               // Add support for EQ3 TRV radiator valves - requires USE_BLE_ESP32
#define USE_EQ3_ESP32                               // Add support for EQ3 TRV radiator valves - requires USE_BLE_ESP32

**Comment by jperquin** [comment]
That seems to have done the trick. Edited the files in gitpod's VSC environment and ran platformio run -e tasmota32-bluetooth again..

Thanks !
