### ISSUE TITLE
EQ3 devices appear only in the console "BLEDevices" but not in MQTT

### ISSUE THREAD

**Issue by dog-rgb** [btsimonh/Tasmota#9]
Hi,

I am using the pre-compiled firmware from this fork and my goal is to get the EQ3 devices visible in iobroker using MQTT. But unfortunately I am getting only a status line in the console where the device is listed:
```
12:34:47.052 MQT: tele/tasmota_5DE928/STATE = {"Time":"2021-12-08T12:34:47","Uptime":"2T03:30:52","UptimeSec":185452,"Heap":122,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":20,"MqttCount":4,"Wifi":{"AP":1,"SSId":"Orion","BSSId":"BA:FB:E4:F7:39:7F","Channel":11,"RSSI":98,"Signal":-51,"LinkCount":2,"Downtime":"0T00:00:46"}}
12:34:47.079 MQT: tele/tasmota_5DE928/BLE = {"Time":"2021-12-08T12:34:47","BLEDevices":{"total":1,"001A2211D4EF":{"i":0,"n":"CC-RT-BLE","r":-76}}}
12:34:47.088 MQT: tele/tasmota_5DE928/BLE = {"Time":"2021-12-08T12:34:47","BLE":{"scans":8940,"adverts":228379,"devices":1,"resets":0}}
```

Also the TRV command does not work:
```
12:56:51.002 CMD: TRV
12:56:51.015 MQT: stat/tasmota_5DE928/RESULT = {"Command":"Unknown"}
12:56:54.394 CMD: TRVperiod
12:56:54.409 MQT: stat/tasmota_5DE928/RESULT = {"Command":"Unknown"}
12:57:46.173 CMD: TRV 001A2211D4EF settemp 21.5
12:57:46.188 MQT: stat/tasmota_5DE928/RESULT = {"Command":"Unknown"}

```
MQTT is configured and the ESP32 device itself is visible in iobroker, but I do not get information of any EQ3 device. What do I miss?

If any additional information is needed, please let me know.

**Comment by Ysbrand** [comment]
Hi,

If the trv command doesn't work, it implies that the EQ3 driver is not part of the build you are using.

Recommend to go to the current released version of TAS (10). When you select the ESP32-Bluetooth version it will come with the EQ3 driver enabled.

**Comment by dog-rgb** [comment]
Thank you. I tried version 10.1.0.1 and at least I get now more information in the console:
`14:41:10.447 MQT: stat/EQ3/XXX = {"cmd":"poll","result":"ok","MAC":"XXX","tas":"tasmota-XXX-XXX","RSSI":-78,"stattime":1639057270,"temp":18.0,"posn":11,"mode":"manual","hassmode":"heat","boost":"inactive","dst":"set","window":"closed","state":"unlocked","battery":"GOOD"}
`
But still no information in iobroker. But I will put the question to tasmota.
